---
abstract: 'Manage processes and retrieve process information on OpenVMS systems'
author:
  - 'Dan Sugalski <dan@sidhe.org>, Craig A. Berry <craigberry@mac.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VMS-Process
no_index:
  directory:
    - t
    - inc
requires: {}
version: 1.09
